# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mdui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1320, 817)
        Dialog.setStyleSheet("")
        self.title = QtWidgets.QLabel(Dialog)
        self.title.setGeometry(QtCore.QRect(110, 240, 1051, 151))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.title.setFont(font)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.go = QtWidgets.QPushButton(Dialog)
        self.go.setGeometry(QtCore.QRect(550, 360, 211, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.go.setFont(font)
        self.go.setObjectName("go")

        self.retranslateUi(Dialog)
        self.go.clicked.connect(Dialog.goin) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.title.setText(_translate("Dialog", "欢迎进入内蒙古大学人车监控系统"))
        self.go.setText(_translate("Dialog", "进入系统"))
# import resources_rc
